#!/usr/bin/env python3
"""Comprehensive zh/zh_TW translations for ALL remaining keys."""
import json, os

D = os.path.join(os.path.dirname(__file__), '..', 'lib', 'l10n')
en = json.load(open(os.path.join(D, 'app_en.arb'), encoding='utf-8'))
zh_data = json.load(open(os.path.join(D, 'app_zh.arb'), encoding='utf-8'))

translations = {
  'repositorySections': '仓库区块',
  'pullRequestNumber': 'PR #{pullRequestNumber}',
  'assignee': '负责人',
  'restoringSession': '正在恢复会话...',
  'helloParams': '你好，{full_name}！',
  'user': '用户',
  'enterSearchQueryIssues': '输入搜索关键词查找 Issue',
  'noIssuesFound': '未找到 Issue',
  'failedToLoadProfile': '加载个人主页失败',
  'unknownUser': '未知用户',
  'admin': '管理员',
  'signOutConfirmMessage': '确定要退出登录吗？',
  'chooseTheme': '选择主题',
  'loadingSettings': '正在加载设置...',
  'userManagementComingSoon': '用户管理即将上线',
  'maxResponseItems': '最大响应条目数',
  'defaultPagingNum': '默认分页数',
  'defaultMaxBlobSize': '默认最大 Blob 大小',
  'maxGitDiffLines': '最大 Git Diff 行数',
  'maxGitDiffLineCharacters': '最大 Diff 行字符数',
  'maxGitDiffFiles': '最大 Diff 文件数',
  'commitFilesPageDefault': '默认提交文件页大小',
  'defaultBranch': '默认分支',
  'searchResults': '搜索结果',
  'searchIssues': '搜索 Issue',
  'noIssues': '暂无 Issue',
  'noComments': '暂无评论',
  'writeComment': '写评论',
  'addComment': '添加评论',
  'noDescription': '暂无描述',
  'noDescriptionProvided': '未提供描述',
  'milestone': '里程碑',
  'noMilestones': '暂无里程碑',
  'newIssue': '新建 Issue',
  'newPullRequest': '新建 Pull Request',
  'viewDiff': '查看 Diff',
  'noChanges': '无变更',
  'noCommits': '暂无提交',
  'noWebhooks': '暂无 Webhook',
  'noActions': '暂无工作流',
  'noJobs': '暂无 Job',
  'noArtifacts': '暂无构建产物',
  'noMembers': '暂无成员',
  'noTeams': '暂无团队',
  'noNotifications': '暂无通知',
  'noUnreadNotifications': '没有未读通知',
  'markAllRead': '全部标为已读',
  'markRead': '标为已读',
  'limited': '受限',
  'actions': 'Actions',
  'unsubscribe': '取消订阅',
  'reviewChanges': '审查变更',
  'diffView': 'Diff 查看',
  'addSshKey': '添加 SSH 密钥',
  'deleteKey': '删除密钥',
  'deleteKeyConfirm': '确定要删除此 SSH 密钥吗？',
  'keyDeleted': '密钥已删除',
  'keyAdded': '密钥已添加',
  'removeDueDate': '移除截止日期',
  'deleteComment': '删除评论',
  'deleteCommentConfirm': '确定要删除此评论吗？',
  'settingsSaved': '设置已保存',
  'headBranch': '源分支',
  'baseBranch': '目标分支',
  'pleaseFillAllFields': '请填写所有必填项',
  'compareVersions': '版本对比',
  'baseRef': '基点（旧版）',
  'headRef': '对比点（新版）',
  'compare': '对比',
  'unifiedView': '统一视图',
  'splitView': '分屏视图',
  'noActivity': '暂无活动',
  'performedAction': '执行了操作',
  'commitRepo': '提交了代码到',
  'createdRepo': '创建了仓库',
  'forkedRepo': 'Fork 了仓库',
  'deletedRepo': '删除了仓库',
  'transferredRepo': '转移了仓库',
  'pushedTag': '推送了标签',
  'deletedTag': '删除了标签',
  'deleteBranch': '删除了分支',
  'createdIssue': '创建了 Issue',
  'closedIssue': '关闭了 Issue',
  'reopenedIssue': '重新打开了 Issue',
  'createdPR': '创建了 PR',
  'mergedPR': '合并了 PR',
  'closedPR': '关闭了 PR',
  'reopenPR': '重新打开了 PR',
  'commentedOnIssue': '评论了 Issue',
  'commentedOnPR': '评论了 PR',
  'updatedWiki': '更新了 Wiki',
  'publishRelease': '发布了版本',
  'approvePR': '批准了 PR',
  'rejectPR': '驳回了 PR',
  'starRepo': '收藏了仓库',
  'watchRepo': '关注了仓库',
  'renameRepo': '重命名了仓库',
  'autoMergePR': '自动合并了 PR',
  'pullReviewDismissed': '驳回了审查',
  'pullRequestReady': '标记 PR 为就绪',
  'mirrorSyncPush': '同步推送了镜像',
  'mirrorSyncCreate': '同步创建了镜像',
  'mirrorSyncDelete': '同步删除了镜像',
  'inRepo': '在',
  'to': '到',
  'from': '从',
  'cloneRepo': '克隆仓库',
  'cloneUrl': '克隆 URL',
  'copyCode': '复制代码',
  'downloadFile': '下载文件',
  'noReadme': '暂无 README',
  'searchCode': '搜索代码',
  'noFiles': '暂无文件',
  'createFile': '新建文件',
  'uploadFile': '上传文件',
  'findFile': '查找文件',
  'addFile': '添加文件',
  'editFile': '编辑文件',
  'deleteFile': '删除文件',
  'fileSaved': '文件已保存',
  'failedToSaveFile': '保存文件失败',
  'discard': '放弃修改',
  'message': '消息',
  'commitMessage': '提交信息',
  'commitMessageHint': '描述你的变更（可选）',
  'lastCommit': '最新提交',
  'commitHistory': '提交历史',
  'failedToLoadComments': '加载评论失败',
  'failedToLoadRepo': '加载仓库失败',
  'noReposFound': '未找到仓库',
  'starredRepos': '已星标的仓库',
  'organisations': '组织',
  'createOrganization': '创建组织',
  'editOrganization': '编辑组织',
  'createRepository': '创建仓库',
  'repoCreated': '仓库 {repoName} 创建成功',
  'initializeWithReadme': '使用 README 初始化',
  'initializeWithReadmeDescription': '添加 README 文件帮助他人了解你的项目',
  'forkRepoConfirm': '这将在你的账号下创建此仓库的 Fork。',
  'participants': '参与者',
  'milestoneProgress': '完成进度',
  'linkedIssues': '关联 Issue',
  'dueDate': '截止日期',
  'selectMilestone': '选择里程碑',
  'total': '总计',
  'complete': '完成',
  'createMilestone': '创建里程碑',
  'editMilestone': '编辑里程碑',
  'deleteMilestone': '删除里程碑',
  'deleteMilestoneConfirm': '确定要删除此里程碑吗？此操作不可撤销。',
  'milestoneDeleted': '里程碑已删除',
  'milestoneTitle': '标题',
  'milestoneDescription': '描述',
  'milestoneDescriptionHint': '描述此里程碑',
  'milestoneDueDate': '截止日期',
  'milestoneState': '状态',
  'milestoneStateOpen': '打开',
  'milestoneStateClosed': '已关闭',
  'createLabel': '创建标签',
  'editLabel': '编辑标签',
  'deleteLabel': '删除标签',
  'deleteLabelConfirm': '确定要删除此标签吗？',
  'labelDeleted': '标签已删除',
  'labelName': '名称',
  'labelNameHint': '例如: bug',
  'labelDescription': '描述',
  'labelDescriptionHint': '可选描述',
  'labelColor': '颜色',
  'labelColorHint': '十六进制颜色，如 #FF0000',
  'webhooks': 'Webhook',
  'webhook': 'Webhook',
  'noWebhooks': '暂无 Webhook',
  'createWebhook': '创建 Webhook',
  'editWebhook': '编辑 Webhook',
  'deleteWebhook': '删除 Webhook',
  'deleteWebhookConfirm': '确定要删除此 Webhook 吗？此操作不可撤销。',
  'webhookDeleted': 'Webhook 已删除',
  'webhookUrl': 'Payload URL',
  'webhookUrlHint': 'https://example.com/webhook',
  'webhookSecret': '密钥',
  'webhookSecretHint': '可选密钥',
  'webhookContentType': '内容类型',
  'webhookContentTypeJson': 'application/json',
  'webhookContentTypeForm': 'application/x-www-form-urlencoded',
  'webhookEvents': '事件',
  'webhookEventsHint': '选择触发 Webhook 的事件',
  'webhookActive': '激活',
  'webhookInactive': '未激活',
  'webhookType': '类型',
  'webhookCreatedAt': '创建时间',
  'webhookUpdatedAt': '更新时间',
  'webhookLastDelivery': '上次投递',
  'webhookSelectAllEvents': '全选',
  'webhookPushEvents': '推送',
  'webhookPullRequestEvents': 'Pull Request',
  'webhookIssuesEvents': 'Issue',
  'webhookCreateEvents': '创建',
  'webhookDeleteEvents': '删除',
  'webhookReleaseEvents': '发布',
  'webhookWikiEvents': 'Wiki',
  'webhookStarEvents': '星标',
  'webhookForkEvents': 'Fork',
  'loginWithOAuth2': '使用 OAuth2 登录',
  'oauth2': 'OAuth2',
  'oauth2Description': '通过 Gitea OAuth2 应用授权',
  'oauth2ClientId': 'Client ID',
  'oauth2ClientSecret': 'Client Secret',
  'oauth2RedirectUri': 'Redirect URI',
  'oauth2RedirectUriHint': 'igitea://oauth/callback',
  'oauth2Authorize': '打开授权页面',
  'oauth2ExchangeCode': '交换 Code 为 Token',
  'oauth2AuthorizationCode': '授权 Code',
  'oauth2AuthorizationCodeHint': '从回调 URL 粘贴 code',
  'oauth2TokenRefreshed': 'Token 已刷新',
  'filterByActor': '按参与者筛选',
  'filterByStatus': '按状态筛选',
  'reviewBody': '审查评论',
  'reviews': '审查',
  'requestChanges': '请求变更',
  'blame': '追溯',
  'pickColor': '选择颜色',
  'sshKeys': 'SSH 密钥',
  'allRepos': '所有仓库',
  'units': '单位',
  'permission': '权限',
  'addReviewerHint': '输入审查者用户名',
  'setDueDate': '设置截止日期',
  'protectBranch': '保护分支',
  'unknownSection': '未知区块',
  'repoList': '仓库列表',
  'noWikiPages': '暂无 Wiki 页面',
  'createFirstWikiPage': '创建第一个页面',
  'saved': '已保存',
  'created': '已创建',
  'wikiPageTitle': '页面标题',
  'wikiPageTitleHint': '例如: Home',
  'wikiPageContent': '内容',
  'wikiPageContentHint': '使用 Markdown 编写...',
  'noWikiPagesDescription': '此仓库还没有任何 Wiki 页面。',
  'lastCommit': '最近提交',
  'igiteaVersion': 'iGitea v0.23.0',
  'enableWiki': '启用 Wiki',
  'enableIssues': '启用 Issue',
  'enablePullRequests': '启用 Pull Request',
  'appTitle': 'iGitea',
  'untitled': '无标题',
  'defaultTheme': '默认主题',
  'allowedReactions': '允许的表情反应',
  'attachments': '附件',
  'enabled': '已启用',
  'maxFiles': '最大文件数',
  'maxSize': '最大大小',
  'allowedTypes': '允许的类型',
  'bytes': '字节',
  'httpGitDisabled': 'HTTP Git 已禁用',
  'lfsDisabled': 'LFS 已禁用',
  'migrationsDisabled': '迁移已禁用',
  'mirrorsDisabled': '镜像已禁用',
  'starsDisabled': '星标已禁用',
  'timeTrackingDisabled': '工时追踪已禁用',
  'schedule': '调度',
  'next': '下次',
  'executions': '执行次数',
  'failedToLoadCronTasks': '加载定时任务失败',
  'noCronTasksFound': '未找到定时任务',
  'cronTriggeredParams': '定时任务 "{name}" 已触发',
  'openedParams': '创建于 {time}',
  'commentsCountParams': '{count} 条评论',
  'updatedParams': '更新于 {time}',
  'commentsParams': '评论 ({count})',
  'files': '文件',
  'mergeable': '可合并',
  'merged': '已合并',
  'draft': '草稿',
  'copyUrl': '复制 URL',
  'urlCopied': 'URL 已复制',
  'emptyDirectory': '空目录',
  'noPullRequests': '暂无 Pull Request',
  'noReleases': '暂无发布',
  'noBranches': '暂无分支',
  'preRelease': '预发布',
  'failedToLoadFile': '加载文件失败',
  'filePreviewNotAvailable': '文件预览不可用',
  'download': '下载',
  'failedToOpenDownloadUrl': '打开下载 URL 失败',
  'noTitle': '无标题',
  'allNotificationsMarkedAsRead': '所有通知已标为已读',
  'preview': '预览',
  'cannotGetFileSha': '无法获取文件 SHA，请重新加载文件。',
  'ok': '确定',
  'changedFiles': '变更的文件',
  'noTags': '暂无标签',
  'protected': '已保护',
  'latestCommit': '最新提交',
  'permissions': '权限',
  'canPush': '可推送',
  'canMerge': '可合并',
  'downloads': '下载',
  'tarball': 'Tar 包',
  'zipball': 'Zip 包',
  'downloadTarball': '下载 Tar 包',
  'downloadZipball': '下载 Zip 包',
  'clear': '清除',
  'filesChanged': '变更的文件',
  'noFilesChanged': '无文件变更',
  'run': '运行',
  'status': '状态',
  'id': 'ID',
  'https': 'HTTPS',
  'ssh': 'SSH',
  'api': 'API',
  'ui': 'UI',
  'wiki': 'Wiki',
  'newWikiPage': '新建 Wiki 页面',
  'editWikiPage': '编辑 Wiki 页面',
  'deleteWikiPage': '删除 Wiki 页面',
  'deleteWikiPageConfirm': '确定要删除此 Wiki 页面吗？此操作不可撤销。',
  'wikiPageDeleted': 'Wiki 页面已删除',
  'webhook': 'Webhook',
  'oauth2': 'OAuth2',
  'actions': 'Actions',
  'jobs': 'Job',
  'branch': '分支',
  'author': '作者',
  'commit': '提交',
  'sha': 'SHA',
}

count = 0
for k, v in translations.items():
    if k in zh_data and zh_data[k] == en.get(k, ''):
        zh_data[k] = v
        count += 1

json.dump(zh_data, open(os.path.join(D, 'app_zh.arb'), 'w', encoding='utf-8'), indent=2, ensure_ascii=False)
open(os.path.join(D, 'app_zh.arb'), 'a').write('\n')

print(f'zh: translated {count} keys')

# Also update zh_TW
tw_data = json.load(open(os.path.join(D, 'app_zh_TW.arb'), encoding='utf-8'))
count_tw = 0
for k, v in translations.items():
    if k in tw_data and tw_data[k] == en.get(k, ''):
        tw = v.replace('仓库', '倉庫').replace('标签', '標籤').replace('设置', '設定') \
              .replace('评论', '評論').replace('合并', '合併').replace('删除', '刪除') \
              .replace('创建', '建立').replace('添加', '新增').replace('刷新', '重新整理') \
              .replace('关闭', '關閉').replace('重命名', '重新命名').replace('错误', '錯誤') \
              .replace('消息', '訊息').replace('包含', '包含').replace('列表', '列表') \
              .replace('代码', '程式碼').replace('文件', '檔案').replace('内容', '內容') \
              .replace('颜色', '顏色').replace('描述', '描述').replace('名称', '名稱') \
              .replace('信息', '資訊').replace('密钥', '金鑰').replace('图标', '圖示') \
              .replace('页面', '頁面').replace('取消', '取消').replace('确认', '確認') \
              .replace('保存', '儲存').replace('编辑', '編輯').replace('删除', '刪除') \
              .replace('新建', '新增').replace('提交', '提交')
        tw_data[k] = tw
        count_tw += 1

json.dump(tw_data, open(os.path.join(D, 'app_zh_TW.arb'), 'w', encoding='utf-8'), indent=2, ensure_ascii=False)
open(os.path.join(D, 'app_zh_TW.arb'), 'a').write('\n')
print(f'zh_TW: translated {count_tw} keys')
