#!/usr/bin/env python3
"""Translate commonly visible UI keys for ja, ko, de, es, fr, pt, ru."""
import json, os

D = os.path.join(os.path.dirname(__file__), '..', 'lib', 'l10n')
en = json.load(open(os.path.join(D, 'app_en.arb'), encoding='utf-8'))

translations = {
  'ja': {
    'appTitle': 'iGitea', 'dashboard': 'ダッシュボード', 'settings': '設定',
    'profile': 'プロフィール', 'search': '検索', 'notifications': '通知',
    'signOut': 'ログアウト', 'signIn': 'ログイン', 'username': 'ユーザー名',
    'password': 'パスワード', 'login': 'ログイン', 'token': 'トークン',
    'cancel': 'キャンセル', 'confirm': '確認', 'save': '保存', 'delete': '削除',
    'edit': '編集', 'create': '作成', 'close': '閉じる', 'reopen': '再開',
    'merge': 'マージ', 'submit': '送信', 'retry': '再試行',
    'loading': '読み込み中...', 'error': 'エラー', 'all': 'すべて',
    'open': '開く', 'closed': '閉じる', 'description': '説明', 'none': 'なし',
    'more': 'もっと', 'add': '追加', 'yes': 'はい', 'no': 'いいえ',
    'unknown': '不明', 'archived': 'アーカイブ済み',
    'repositories': 'リポジトリ', 'issues': 'Issue', 'pullRequests': 'Pull Request',
    'releases': 'リリース', 'branches': 'ブランチ', 'code': 'コード',
    'tags': 'タグ', 'wiki': 'Wiki', 'stars': 'スター', 'forks': 'フォーク',
    'watchers': 'ウォッチャー', 'milestones': 'マイルストーン',
    'comments': 'コメント', 'language': '言語', 'theme': 'テーマ',
    'themeLight': 'ライト', 'themeDark': 'ダーク', 'themeSystem': 'システム',
    'version': 'バージョン', 'url': 'URL',
    'noData': 'データなし', 'noResults': '結果なし',
    'yourRepositories': 'マイリポジトリ', 'repos': 'リポジトリ',
    'followers': 'フォロワー', 'following': 'フォロー中',
    'quickActions': 'クイック操作',
    'myIssues': 'マイ Issue', 'myRepos': 'マイリポジトリ', 'myStars': 'スター',
    'noRepositoriesFound': 'リポジトリが見つかりません',
    'repository': 'リポジトリ',
    'repositoryName': 'リポジトリ名', 'repositoryNameRequired': 'リポジトリ名は必須です',
    'descriptionHint': 'リポジトリの簡単な説明',
    'publicDescription': '誰でもこのリポジトリを見ることができます',
    'searchRepositoriesHint': 'リポジトリを検索',
    'serverUrl': 'サーバーURL', 'enterUsername': 'ユーザー名を入力',
    'pleaseEnterUsername': 'ユーザー名を入力してください',
    'enterPassword': 'パスワードを入力',
    'pleaseEnterPassword': 'パスワードを入力してください',
    'pleaseEnterServerUrl': 'サーバーURLを入力してください',
    'pleaseEnterValidUrl': '有効なURLを入力してください',
    'connectToGitea': 'Giteaインスタンスに接続',
    'signInWithToken': 'トークンでログイン',
    'joinedOn': '{date} に参加',
    'bio': '自己紹介', 'website': 'ウェブサイト',
    'repoList': 'リポジトリ一覧',
    'searchIssues': 'Issueを検索', 'noIssues': 'Issueなし',
    'noComments': 'コメントなし', 'writeComment': 'コメントを書く',
    'addComment': 'コメントを追加',
    'noDescription': '説明なし', 'noDescriptionProvided': '説明がありません',
    'milestone': 'マイルストーン', 'noMilestones': 'マイルストーンなし',
    'newIssue': '新規Issue', 'newPullRequest': '新規Pull Request',
    'viewDiff': '差分を見る', 'noChanges': '変更なし',
    'noContent': '内容なし', 'noCommits': 'コミットなし',
    'noLabels': 'ラベルなし', 'noWebhooks': 'Webhookなし',
    'noActions': 'ワークフローなし', 'noJobs': 'ジョブなし',
    'noArtifacts': 'アーティファクトなし', 'noMembers': 'メンバーなし',
    'noTeams': 'チームなし', 'noWikiPages': 'Wikiページなし',
    'noNotifications': '通知なし', 'noUnreadNotifications': '未読通知なし',
    'markAllRead': 'すべて既読にする', 'markRead': '既読にする',
    'public': '公開', 'private': '非公開', 'limited': '制限付き',
    'actions': 'Actions', 'artifacts': 'アーティファクト',
    'subscribe': '購読', 'unsubscribe': '購読解除',
    'requestReviewers': 'レビュアーを依頼', 'reviewChanges': '変更をレビュー',
    'approve': '承認', 'requestChanges': '変更を依頼',
    'comment': 'コメント', 'blame': ' blame',
    'diffView': '差分表示', 'configuration': '設定',
    'sshKeys': 'SSH鍵', 'addSshKey': 'SSH鍵を追加',
    'deleteKey': '鍵を削除', 'deleteKeyConfirm': 'このSSH鍵を削除してもよろしいですか？',
    'keyDeleted': '鍵を削除しました', 'keyAdded': '鍵を追加しました',
    'branchProtection': 'ブランチ保護', 'protectBranch': 'ブランチを保護',
    'setDueDate': '期限を設定', 'removeDueDate': '期限を削除',
    'topics': 'トピック', 'noTopics': 'トピックなし',
    'deleteComment': 'コメントを削除',
    'deleteCommentConfirm': 'このコメントを削除してもよろしいですか？',
    'settingsSaved': '設定を保存しました',
    'defaultBranch': 'デフォルトブランチ',
    'headBranch': '送信元ブランチ', 'baseBranch': '送信先ブランチ',
    'pleaseFillAllFields': '必須項目をすべて入力してください',
    'compareVersions': 'バージョン比較', 'compare': '比較',
    'unifiedView': '統一表示', 'splitView': '分割表示',
    'recentActivity': '最近のアクティビティ', 'noActivity': 'アクティビティなし',
    'createdRepo': 'リポジトリを作成', 'forkedRepo': 'フォークしました',
    'deletedRepo': 'リポジトリを削除', 'pushedTag': 'タグをプッシュ',
    'deletedTag': 'タグを削除', 'deleteBranch': 'ブランチを削除',
    'createdIssue': 'Issueを作成', 'closedIssue': 'Issueをクローズ',
    'reopenedIssue': 'Issueを再開', 'createdPR': 'PRを作成',
    'mergedPR': 'PRをマージ', 'closedPR': 'PRをクローズ',
    'reopenPR': 'PRを再開', 'commentedOnIssue': 'Issueにコメント',
    'commentedOnPR': 'PRにコメント', 'updatedWiki': 'Wikiを更新',
    'publishRelease': 'リリースを公開', 'approvePR': 'PRを承認',
    'starRepo': 'スターを付けた', 'renameRepo': 'リポジトリ名を変更',
    'autoMergePR': 'PRを自動マージ',
    'inRepo': 'で', 'to': 'へ', 'from': 'から',
    'noMilestones': 'マイルストーンなし',
    'createMilestone': 'マイルストーンを作成',
    'editMilestone': 'マイルストーンを編集',
    'deleteMilestone': 'マイルストーンを削除',
    'deleteMilestoneConfirm': 'このマイルストーンを削除してもよろしいですか？',
    'milestoneDeleted': 'マイルストーンを削除しました',
    'milestoneTitle': 'タイトル', 'milestoneDueDate': '期限',
    'milestoneState': '状態', 'milestoneStateOpen': 'オープン',
    'milestoneStateClosed': 'クローズ',
    'createLabel': 'ラベルを作成', 'editLabel': 'ラベルを編集',
    'deleteLabel': 'ラベルを削除', 'deleteLabelConfirm': 'このラベルを削除してもよろしいですか？',
    'labelDeleted': 'ラベルを削除しました',
    'labelName': '名前', 'labelNameHint': '例: bug',
    'labelDescription': '説明', 'labelDescriptionHint': '説明（任意）',
    'labelColor': '色', 'labelColorHint': '16進数カラー（例: #FF0000）',
    'createWebhook': 'Webhookを作成', 'editWebhook': 'Webhookを編集',
    'deleteWebhook': 'Webhookを削除',
    'deleteWebhookConfirm': 'このWebhookを削除してもよろしいですか？',
    'webhookDeleted': 'Webhookを削除しました',
    'webhookUrl': 'Payload URL',
    'webhookActive': 'アクティブ', 'webhookInactive': '非アクティブ',
    'webhookType': 'タイプ', 'webhookCreatedAt': '作成日',
    'webhookUpdatedAt': '更新日',
    'webhookPushEvents': 'プッシュ',
    'webhookPullRequestEvents': 'Pull Request',
    'webhookIssuesEvents': 'Issue',
    'webhookCreateEvents': '作成', 'webhookDeleteEvents': '削除',
    'webhookReleaseEvents': 'リリース', 'webhookWikiEvents': 'Wiki',
    'webhookStarEvents': 'スター', 'webhookForkEvents': 'Fork',
    'filterByActor': '実行者で絞り込み',
    'filterByStatus': 'ステータスで絞り込み',
    'reviewBody': 'レビューコメント', 'reviews': 'レビュー',
    'pickColor': '色を選択',
    'sshKeys': 'SSH鍵',
    'allRepos': 'すべてのリポジトリ',
    'units': '単位', 'permission': '権限',
    'commit': 'コミット', 'sha': 'SHA',
    'branch': 'ブランチ', 'author': '作成者',
    'jobs': 'ジョブ', 'status': 'ステータス',
    'https': 'HTTPS', 'ssh': 'SSH', 'id': 'ID', 'api': 'API', 'ui': 'UI',
    'filesChanged': '変更されたファイル',
    'noFilesChanged': '変更されたファイルはありません',
    'clear': 'クリア',
    'untitled': '無題',
    'download': 'ダウンロード',
    'preview': 'プレビュー',
    'ok': 'OK',
  },
  'ko': {
    'appTitle': 'iGitea', 'dashboard': '대시보드', 'settings': '설정',
    'profile': '프로필', 'search': '검색', 'notifications': '알림',
    'signOut': '로그아웃', 'signIn': '로그인', 'username': '사용자명',
    'password': '비밀번호', 'login': '로그인', 'token': '토큰',
    'cancel': '취소', 'confirm': '확인', 'save': '저장', 'delete': '삭제',
    'edit': '편집', 'create': '생성', 'close': '닫기', 'reopen': '재열기',
    'merge': '병합', 'submit': '제출', 'retry': '재시도',
    'loading': '로딩 중...', 'error': '오류', 'all': '전체',
    'open': '열기', 'closed': '닫힘', 'description': '설명', 'none': '없음',
    'more': '더보기', 'add': '추가', 'yes': '예', 'no': '아니오',
    'unknown': '알 수 없음',
    'repositories': '저장소', 'issues': '이슈', 'pullRequests': 'Pull Request',
    'releases': '릴리스', 'branches': '브랜치', 'code': '코드',
    'tags': '태그', 'wiki': 'Wiki', 'stars': '별표', 'forks': '포크',
    'milestones': '마일스톤', 'comments': '댓글',
    'language': '언어', 'theme': '테마',
    'themeLight': '라이트', 'themeDark': '다크', 'themeSystem': '시스템',
    'version': '버전', 'url': 'URL',
    'noData': '데이터 없음', 'noResults': '결과 없음',
    'yourRepositories': '내 저장소', 'repos': '저장소',
    'followers': '팔로워', 'following': '팔로잉',
    'quickActions': '빠른 작업',
    'myIssues': '내 이슈', 'myRepos': '내 저장소', 'myStars': '별표',
    'noRepositoriesFound': '저장소를 찾을 수 없습니다',
    'repository': '저장소',
    'repositoryName': '저장소 이름', 'repositoryNameRequired': '저장소 이름은 필수입니다',
    'descriptionHint': '저장소에 대한 간단한 설명',
    'searchRepositoriesHint': '저장소 검색',
    'serverUrl': '서버 URL', 'enterUsername': '사용자명 입력',
    'pleaseEnterUsername': '사용자명을 입력하세요',
    'enterPassword': '비밀번호 입력',
    'pleaseEnterPassword': '비밀번호를 입력하세요',
    'pleaseEnterServerUrl': '서버 URL을 입력하세요',
    'pleaseEnterValidUrl': '유효한 URL을 입력하세요',
    'connectToGitea': 'Gitea 인스턴스에 연결',
    'signInWithToken': '토큰으로 로그인',
    'joinedOn': '{date}에 가입',
    'bio': '자기소개', 'website': '웹사이트',
    'repoList': '저장소 목록',
    'searchIssues': '이슈 검색', 'noIssues': '이슈 없음',
    'noComments': '댓글 없음', 'writeComment': '댓글 작성',
    'addComment': '댓글 추가',
    'noDescription': '설명 없음', 'noDescriptionProvided': '설명이 제공되지 않았습니다',
    'milestone': '마일스톤', 'noMilestones': '마일스톤 없음',
    'newIssue': '새 이슈', 'newPullRequest': '새 Pull Request',
    'viewDiff': '차이 보기', 'noChanges': '변경 없음',
    'noContent': '내용 없음', 'noCommits': '커밋 없음',
    'noLabels': '라벨 없음', 'noWebhooks': '웹훅 없음',
    'noActions': '워크플로우 없음', 'noJobs': '작업 없음',
    'noArtifacts': '아티팩트 없음', 'noMembers': '멤버 없음',
    'noTeams': '팀 없음', 'noWikiPages': 'Wiki 페이지 없음',
    'noNotifications': '알림 없음', 'noUnreadNotifications': '읽지 않은 알림 없음',
    'markAllRead': '모두 읽음 표시', 'markRead': '읽음 표시',
    'public': '공개', 'private': '비공개', 'limited': '제한',
    'actions': 'Actions', 'artifacts': '아티팩트',
    'subscribe': '구독', 'unsubscribe': '구독 취소',
    'requestReviewers': '리뷰어 요청', 'reviewChanges': '변경 검토',
    'approve': '승인', 'requestChanges': '변경 요청',
    'comment': '댓글', 'blame': 'Blame',
    'diffView': '차이 보기', 'configuration': '설정',
    'sshKeys': 'SSH 키', 'addSshKey': 'SSH 키 추가',
    'deleteKey': '키 삭제', 'deleteKeyConfirm': '이 SSH 키를 삭제하시겠습니까?',
    'keyDeleted': '키가 삭제되었습니다', 'keyAdded': '키가 추가되었습니다',
    'branchProtection': '브랜치 보호', 'protectBranch': '브랜치 보호',
    'setDueDate': '마감일 설정', 'removeDueDate': '마감일 제거',
    'topics': '토픽', 'noTopics': '토픽 없음',
    'deleteComment': '댓글 삭제',
    'deleteCommentConfirm': '이 댓글을 삭제하시겠습니까?',
    'settingsSaved': '설정이 저장되었습니다',
    'defaultBranch': '기본 브랜치',
    'headBranch': '소스 브랜치', 'baseBranch': '대상 브랜치',
    'pleaseFillAllFields': '모든 필수 항목을 입력하세요',
    'compareVersions': '버전 비교', 'compare': '비교',
    'unifiedView': '통합 보기', 'splitView': '분할 보기',
    'recentActivity': '최근 활동', 'noActivity': '활동 없음',
    'createdRepo': '저장소를 생성했습니다',
    'forkedRepo': '포크했습니다', 'deletedRepo': '저장소를 삭제했습니다',
    'createdIssue': '이슈를 생성했습니다',
    'closedIssue': '이슈를 닫았습니다',
    'reopenedIssue': '이슈를 재열었습니다',
    'createdPR': 'PR을 생성했습니다',
    'mergedPR': 'PR을 병합했습니다',
    'closedPR': 'PR을 닫았습니다',
    'reopenPR': 'PR을 재열었습니다',
    'commentedOnIssue': '이슈에 댓글을 남겼습니다',
    'commentedOnPR': 'PR에 댓글을 남겼습니다',
    'updatedWiki': 'Wiki를 업데이트했습니다',
    'publishRelease': '릴리스를 발행했습니다',
    'approvePR': 'PR을 승인했습니다',
    'starRepo': '저장소에 별표를 표시했습니다',
    'renameRepo': '저장소 이름을 변경했습니다',
    'autoMergePR': 'PR을 자동 병합했습니다',
    'inRepo': '에서', 'to': '으로', 'from': '에서',
    'createMilestone': '마일스톤 생성',
    'editMilestone': '마일스톤 편집',
    'deleteMilestone': '마일스톤 삭제',
    'deleteMilestoneConfirm': '이 마일스톤을 삭제하시겠습니까?',
    'milestoneDeleted': '마일스톤이 삭제되었습니다',
    'milestoneTitle': '제목', 'milestoneDueDate': '마감일',
    'milestoneState': '상태', 'milestoneStateOpen': '열림',
    'milestoneStateClosed': '닫힘',
    'createLabel': '라벨 생성', 'editLabel': '라벨 편집',
    'deleteLabel': '라벨 삭제', 'deleteLabelConfirm': '이 라벨을 삭제하시겠습니까?',
    'labelDeleted': '라벨이 삭제되었습니다',
    'labelName': '이름', 'labelNameHint': '예: bug',
    'labelDescription': '설명', 'labelDescriptionHint': '설명 (선택사항)',
    'labelColor': '색상', 'labelColorHint': '16진수 색상 (예: #FF0000)',
    'createWebhook': '웹훅 생성', 'editWebhook': '웹훅 편집',
    'deleteWebhook': '웹훅 삭제',
    'deleteWebhookConfirm': '이 웹훅을 삭제하시겠습니까?',
    'webhookDeleted': '웹훅이 삭제되었습니다',
    'webhookActive': '활성', 'webhookInactive': '비활성',
    'webhookType': '유형', 'webhookCreatedAt': '생성일',
    'webhookUpdatedAt': '업데이트일',
    'webhookPushEvents': '푸시', 'webhookPullRequestEvents': 'Pull Request',
    'webhookIssuesEvents': '이슈', 'webhookCreateEvents': '생성',
    'webhookDeleteEvents': '삭제', 'webhookReleaseEvents': '릴리스',
    'webhookWikiEvents': 'Wiki', 'webhookStarEvents': '별표',
    'webhookForkEvents': '포크',
    'filterByActor': '실행자로 필터', 'filterByStatus': '상태로 필터',
    'reviewBody': '리뷰 코멘트', 'reviews': '리뷰',
    'pickColor': '색상 선택',
    'sshKeys': 'SSH 키',
    'allRepos': '모든 저장소',
    'units': '단위', 'permission': '권한',
    'commit': '커밋', 'sha': 'SHA',
    'branch': '브랜치', 'author': '작성자',
    'jobs': '작업', 'status': '상태',
    'https': 'HTTPS', 'ssh': 'SSH', 'id': 'ID', 'api': 'API', 'ui': 'UI',
    'filesChanged': '변경된 파일',
    'noFilesChanged': '변경된 파일 없음',
    'clear': '지우기',
    'untitled': '제목 없음',
    'download': '다운로드',
    'preview': '미리보기',
    'ok': '확인',
  },
  'de': {
    'dashboard': 'Dashboard', 'settings': 'Einstellungen',
    'profile': 'Profil', 'search': 'Suche', 'notifications': 'Benachrichtigungen',
    'signOut': 'Abmelden', 'signIn': 'Anmelden', 'username': 'Benutzername',
    'password': 'Passwort', 'login': 'Anmelden',
    'cancel': 'Abbrechen', 'confirm': 'Bestätigen', 'save': 'Speichern',
    'delete': 'Löschen', 'edit': 'Bearbeiten', 'create': 'Erstellen',
    'close': 'Schließen', 'reopen': 'Wieder öffnen', 'merge': 'Zusammenführen',
    'submit': 'Absenden', 'retry': 'Wiederholen',
    'loading': 'Laden...', 'error': 'Fehler', 'all': 'Alle',
    'open': 'Offen', 'closed': 'Geschlossen', 'description': 'Beschreibung',
    'none': 'Keine', 'more': 'Mehr', 'add': 'Hinzufügen',
    'yes': 'Ja', 'no': 'Nein', 'unknown': 'Unbekannt',
    'repositories': 'Repositorys', 'issues': 'Issues',
    'pullRequests': 'Pull Requests', 'releases': 'Releases',
    'branches': 'Branches', 'code': 'Code', 'tags': 'Tags',
    'wiki': 'Wiki', 'stars': 'Sterne', 'forks': 'Forks',
    'milestones': 'Meilensteine', 'comments': 'Kommentare',
    'language': 'Sprache', 'theme': 'Design',
    'themeLight': 'Hell', 'themeDark': 'Dunkel', 'themeSystem': 'System',
    'version': 'Version', 'url': 'URL',
    'noData': 'Keine Daten', 'noResults': 'Keine Ergebnisse',
    'yourRepositories': 'Ihre Repositorys', 'repos': 'Repositorys',
    'followers': 'Follower', 'following': 'Folge ich',
    'quickActions': 'Schnellaktionen',
    'myIssues': 'Meine Issues', 'myRepos': 'Meine Repositorys',
    'myStars': 'Meine Sterne',
    'noRepositoriesFound': 'Keine Repositorys gefunden',
    'repository': 'Repository',
    'repositoryName': 'Repository-Name',
    'searchRepositoriesHint': 'Repositorys durchsuchen',
    'serverUrl': 'Server-URL',
    'pleaseEnterServerUrl': 'Bitte geben Sie eine Server-URL ein',
    'pleaseEnterValidUrl': 'Bitte geben Sie eine gültige URL ein',
    'connectToGitea': 'Mit Ihrer Gitea-Instanz verbinden',
    'signInWithToken': 'Mit Token anmelden',
    'joinedOn': 'Beigetreten am {date}',
    'bio': 'Bio', 'website': 'Webseite',
    'repoList': 'Repository-Liste',
    'noIssues': 'Keine Issues', 'noComments': 'Keine Kommentare',
    'writeComment': 'Kommentar schreiben', 'addComment': 'Kommentar hinzufügen',
    'noDescription': 'Keine Beschreibung',
    'milestone': 'Meilenstein', 'noMilestones': 'Keine Meilensteine',
    'newIssue': 'Neues Issue', 'newPullRequest': 'Neuer Pull Request',
    'viewDiff': 'Diff anzeigen', 'noChanges': 'Keine Änderungen',
    'noContent': 'Kein Inhalt', 'noCommits': 'Keine Commits',
    'noLabels': 'Keine Labels', 'noWebhooks': 'Keine Webhooks',
    'noActions': 'Keine Workflows', 'noJobs': 'Keine Jobs',
    'noMembers': 'Keine Mitglieder', 'noTeams': 'Keine Teams',
    'noWikiPages': 'Keine Wiki-Seiten',
    'noNotifications': 'Keine Benachrichtigungen',
    'markAllRead': 'Alle als gelesen markieren',
    'markRead': 'Als gelesen markieren',
    'public': 'Öffentlich', 'private': 'Privat', 'limited': 'Eingeschränkt',
    'subscribe': 'Abonnieren', 'unsubscribe': 'Abo kündigen',
    'requestReviewers': 'Reviewer anfordern',
    'approve': 'Genehmigen', 'requestChanges': 'Änderungen anfordern',
    'comment': 'Kommentar', 'configuration': 'Konfiguration',
    'sshKeys': 'SSH-Schlüssel',
    'branchProtection': 'Branch-Schutz',
    'protectBranch': 'Branch schützen',
    'setDueDate': 'Fälligkeitsdatum setzen',
    'topics': 'Themen',
    'settingsSaved': 'Einstellungen gespeichert',
    'defaultBranch': 'Standard-Branch',
    'headBranch': 'Quell-Branch', 'baseBranch': 'Ziel-Branch',
    'pleaseFillAllFields': 'Bitte füllen Sie alle Pflichtfelder aus',
    'compareVersions': 'Versionen vergleichen', 'compare': 'Vergleichen',
    'recentActivity': 'Letzte Aktivität', 'noActivity': 'Keine Aktivität',
    'createdRepo': 'Repository erstellt',
    'createdIssue': 'Issue erstellt',
    'closedIssue': 'Issue geschlossen',
    'createdPR': 'PR erstellt', 'mergedPR': 'PR gemergt',
    'closedPR': 'PR geschlossen',
    'commentedOnIssue': 'Issue kommentiert',
    'commentedOnPR': 'PR kommentiert',
    'inRepo': 'in', 'to': 'nach', 'from': 'von',
    'createMilestone': 'Meilenstein erstellen',
    'editMilestone': 'Meilenstein bearbeiten',
    'deleteMilestone': 'Meilenstein löschen',
    'milestoneTitle': 'Titel', 'milestoneDueDate': 'Fälligkeitsdatum',
    'milestoneState': 'Status', 'milestoneStateOpen': 'Offen',
    'milestoneStateClosed': 'Geschlossen',
    'createLabel': 'Label erstellen', 'editLabel': 'Label bearbeiten',
    'deleteLabel': 'Label löschen',
    'labelName': 'Name', 'labelNameHint': 'z.B. bug',
    'labelColor': 'Farbe', 'labelColorHint': 'Hex-Farbe, z.B. #FF0000',
    'createWebhook': 'Webhook erstellen',
    'editWebhook': 'Webhook bearbeiten',
    'deleteWebhook': 'Webhook löschen',
    'webhookActive': 'Aktiv', 'webhookInactive': 'Inaktiv',
    'webhookType': 'Typ', 'webhookCreatedAt': 'Erstellt am',
    'webhookUpdatedAt': 'Aktualisiert am',
    'filterByActor': 'Nach Akteur filtern',
    'filterByStatus': 'Nach Status filtern',
    'reviews': 'Reviews',
    'pickColor': 'Farbe auswählen',
    'allRepos': 'Alle Repositorys',
    'units': 'Einheiten', 'permission': 'Berechtigung',
    'commit': 'Commit', 'sha': 'SHA',
    'branch': 'Branch', 'author': 'Autor',
    'jobs': 'Jobs', 'status': 'Status',
    'https': 'HTTPS', 'ssh': 'SSH', 'id': 'ID', 'api': 'API', 'ui': 'UI',
    'filesChanged': 'Geänderte Dateien',
    'noFilesChanged': 'Keine Dateien geändert',
    'clear': 'Löschen',
    'untitled': 'Unbenannt',
    'download': 'Herunterladen',
    'preview': 'Vorschau',
    'ok': 'OK',
  },
  'es': {
    'dashboard': 'Panel', 'settings': 'Ajustes', 'profile': 'Perfil',
    'search': 'Buscar', 'notifications': 'Notificaciones',
    'signOut': 'Cerrar sesión', 'signIn': 'Iniciar sesión',
    'username': 'Nombre de usuario', 'password': 'Contraseña',
    'login': 'Iniciar sesión', 'cancel': 'Cancelar',
    'confirm': 'Confirmar', 'save': 'Guardar', 'delete': 'Eliminar',
    'edit': 'Editar', 'create': 'Crear', 'close': 'Cerrar',
    'reopen': 'Reabrir', 'merge': 'Fusionar', 'submit': 'Enviar',
    'retry': 'Reintentar', 'loading': 'Cargando...', 'error': 'Error',
    'all': 'Todo', 'open': 'Abierto', 'closed': 'Cerrado',
    'description': 'Descripción', 'none': 'Ninguno',
    'more': 'Más', 'add': 'Añadir', 'yes': 'Sí', 'no': 'No',
    'unknown': 'Desconocido',
    'repositories': 'Repositorios', 'issues': 'Issues',
    'pullRequests': 'Pull Requests', 'releases': 'Lanzamientos',
    'branches': 'Ramas', 'code': 'Código', 'tags': 'Etiquetas',
    'wiki': 'Wiki', 'stars': 'Estrellas', 'forks': 'Forks',
    'milestones': 'Hitos', 'comments': 'Comentarios',
    'language': 'Idioma', 'theme': 'Tema',
    'themeLight': 'Claro', 'themeDark': 'Oscuro', 'themeSystem': 'Sistema',
    'version': 'Versión', 'url': 'URL',
    'noData': 'Sin datos', 'noResults': 'Sin resultados',
    'repos': 'Repos', 'followers': 'Seguidores',
    'following': 'Siguiendo', 'quickActions': 'Acciones rápidas',
    'myIssues': 'Mis Issues', 'myRepos': 'Mis repositorios',
    'myStars': 'Mis estrellas',
    'noRepositoriesFound': 'No se encontraron repositorios',
    'repository': 'Repositorio',
    'repositoryName': 'Nombre del repositorio',
    'searchRepositoriesHint': 'Buscar repositorios',
    'serverUrl': 'URL del servidor',
    'pleaseEnterServerUrl': 'Ingrese una URL de servidor',
    'pleaseEnterValidUrl': 'Ingrese una URL válida',
    'connectToGitea': 'Conectarse a su instancia Gitea',
    'signInWithToken': 'Iniciar sesión con Token',
    'joinedOn': 'Se unió el {date}',
    'bio': 'Biografía', 'website': 'Sitio web',
    'repoList': 'Lista de repositorios',
    'searchIssues': 'Buscar issues', 'noIssues': 'Sin issues',
    'noComments': 'Sin comentarios', 'writeComment': 'Escribir comentario',
    'addComment': 'Añadir comentario',
    'noDescription': 'Sin descripción',
    'milestone': 'Hito', 'noMilestones': 'Sin hitos',
    'newIssue': 'Nuevo Issue', 'newPullRequest': 'Nuevo Pull Request',
    'viewDiff': 'Ver Diff', 'noChanges': 'Sin cambios',
    'noContent': 'Sin contenido', 'noCommits': 'Sin commits',
    'noLabels': 'Sin etiquetas', 'noWebhooks': 'Sin webhooks',
    'noActions': 'Sin flujos de trabajo', 'noJobs': 'Sin trabajos',
    'noMembers': 'Sin miembros', 'noTeams': 'Sin equipos',
    'noWikiPages': 'Sin páginas Wiki',
    'noNotifications': 'Sin notificaciones',
    'markAllRead': 'Marcar todo como leído',
    'markRead': 'Marcar como leído',
    'public': 'Público', 'private': 'Privado', 'limited': 'Limitado',
    'subscribe': 'Suscribirse', 'unsubscribe': 'Cancelar suscripción',
    'requestReviewers': 'Solicitar revisores',
    'approve': 'Aprobar', 'requestChanges': 'Solicitar cambios',
    'comment': 'Comentario', 'configuration': 'Configuración',
    'sshKeys': 'Claves SSH',
    'settingsSaved': 'Ajustes guardados',
    'defaultBranch': 'Rama por defecto',
    'headBranch': 'Rama fuente', 'baseBranch': 'Rama destino',
    'pleaseFillAllFields': 'Complete todos los campos obligatorios',
    'compareVersions': 'Comparar versiones', 'compare': 'Comparar',
    'recentActivity': 'Actividad reciente', 'noActivity': 'Sin actividad',
    'inRepo': 'en', 'to': 'a', 'from': 'de',
    'createMilestone': 'Crear hito', 'editMilestone': 'Editar hito',
    'deleteMilestone': 'Eliminar hito',
    'milestoneTitle': 'Título', 'milestoneDueDate': 'Fecha de vencimiento',
    'milestoneState': 'Estado', 'milestoneStateOpen': 'Abierto',
    'milestoneStateClosed': 'Cerrado',
    'createLabel': 'Crear etiqueta', 'editLabel': 'Editar etiqueta',
    'deleteLabel': 'Eliminar etiqueta',
    'labelName': 'Nombre', 'labelNameHint': 'ej. bug',
    'labelColor': 'Color',
    'createWebhook': 'Crear Webhook',
    'editWebhook': 'Editar Webhook',
    'deleteWebhook': 'Eliminar Webhook',
    'webhookActive': 'Activo', 'webhookInactive': 'Inactivo',
    'webhookType': 'Tipo',
    'filterByActor': 'Filtrar por actor',
    'filterByStatus': 'Filtrar por estado',
    'reviews': 'Revisiones',
    'allRepos': 'Todos los repositorios',
    'units': 'Unidades', 'permission': 'Permiso',
    'commit': 'Commit', 'sha': 'SHA',
    'branch': 'Rama', 'author': 'Autor',
    'jobs': 'Trabajos', 'status': 'Estado',
    'https': 'HTTPS', 'ssh': 'SSH', 'id': 'ID', 'api': 'API', 'ui': 'UI',
    'filesChanged': 'Archivos cambiados',
    'noFilesChanged': 'Sin archivos cambiados',
    'clear': 'Limpiar', 'untitled': 'Sin título',
    'download': 'Descargar', 'preview': 'Vista previa',
    'ok': 'OK',
  },
  'fr': {
    'dashboard': 'Tableau de bord', 'settings': 'Paramètres',
    'profile': 'Profil', 'search': 'Rechercher',
    'notifications': 'Notifications', 'signOut': 'Déconnexion',
    'signIn': 'Connexion', 'username': 'Nom d\'utilisateur',
    'password': 'Mot de passe', 'login': 'Connexion',
    'cancel': 'Annuler', 'confirm': 'Confirmer', 'save': 'Enregistrer',
    'delete': 'Supprimer', 'edit': 'Modifier', 'create': 'Créer',
    'close': 'Fermer', 'reopen': 'Rouvrir', 'merge': 'Fusionner',
    'submit': 'Soumettre', 'retry': 'Réessayer',
    'loading': 'Chargement...', 'error': 'Erreur',
    'all': 'Tout', 'open': 'Ouvert', 'closed': 'Fermé',
    'description': 'Description', 'none': 'Aucun',
    'more': 'Plus', 'add': 'Ajouter', 'yes': 'Oui', 'no': 'Non',
    'unknown': 'Inconnu',
    'repositories': 'Dépôts', 'issues': 'Issues',
    'pullRequests': 'Pull Requests', 'releases': 'Versions',
    'branches': 'Branches', 'code': 'Code', 'tags': 'Étiquettes',
    'wiki': 'Wiki', 'stars': 'Étoiles', 'forks': 'Forks',
    'milestones': 'Jalons', 'comments': 'Commentaires',
    'language': 'Langue', 'theme': 'Thème',
    'themeLight': 'Clair', 'themeDark': 'Sombre', 'themeSystem': 'Système',
    'version': 'Version', 'url': 'URL',
    'noData': 'Pas de données', 'noResults': 'Aucun résultat',
    'repos': 'Dépôts', 'followers': 'Abonnés',
    'following': 'Abonnements', 'quickActions': 'Actions rapides',
    'myIssues': 'Mes Issues', 'myRepos': 'Mes dépôts',
    'myStars': 'Mes étoiles',
    'noRepositoriesFound': 'Aucun dépôt trouvé',
    'repository': 'Dépôt',
    'repositoryName': 'Nom du dépôt',
    'searchRepositoriesHint': 'Rechercher des dépôts',
    'serverUrl': 'URL du serveur',
    'pleaseEnterServerUrl': 'Veuillez saisir une URL de serveur',
    'pleaseEnterValidUrl': 'Veuillez saisir une URL valide',
    'connectToGitea': 'Connectez-vous à votre instance Gitea',
    'signInWithToken': 'Connexion avec Token',
    'joinedOn': 'Inscrit le {date}',
    'bio': 'Bio', 'website': 'Site web',
    'repoList': 'Liste des dépôts',
    'searchIssues': 'Rechercher des issues',
    'noIssues': 'Aucune issue', 'noComments': 'Aucun commentaire',
    'writeComment': 'Écrire un commentaire',
    'addComment': 'Ajouter un commentaire',
    'noDescription': 'Pas de description',
    'milestone': 'Jalon', 'noMilestones': 'Aucun jalon',
    'newIssue': 'Nouvelle issue', 'newPullRequest': 'Nouveau Pull Request',
    'viewDiff': 'Voir le diff', 'noChanges': 'Aucun changement',
    'noContent': 'Pas de contenu', 'noCommits': 'Aucun commit',
    'noLabels': 'Aucune étiquette', 'noWebhooks': 'Aucun webhook',
    'noActions': 'Aucun workflow', 'noJobs': 'Aucun job',
    'noMembers': 'Aucun membre', 'noTeams': 'Aucune équipe',
    'noWikiPages': 'Aucune page Wiki',
    'noNotifications': 'Aucune notification',
    'markAllRead': 'Tout marquer comme lu',
    'markRead': 'Marquer comme lu',
    'public': 'Public', 'private': 'Privé', 'limited': 'Limité',
    'subscribe': 'S\'abonner', 'unsubscribe': 'Se désabonner',
    'requestReviewers': 'Demander des relecteurs',
    'approve': 'Approuver', 'requestChanges': 'Demander des modifications',
    'comment': 'Commentaire', 'configuration': 'Configuration',
    'sshKeys': 'Clés SSH',
    'settingsSaved': 'Paramètres enregistrés',
    'defaultBranch': 'Branche par défaut',
    'headBranch': 'Branche source', 'baseBranch': 'Branche cible',
    'pleaseFillAllFields': 'Veuillez remplir tous les champs obligatoires',
    'compareVersions': 'Comparer les versions', 'compare': 'Comparer',
    'recentActivity': 'Activité récente', 'noActivity': 'Aucune activité',
    'inRepo': 'dans', 'to': 'vers', 'from': 'de',
    'createMilestone': 'Créer un jalon',
    'editMilestone': 'Modifier le jalon',
    'deleteMilestone': 'Supprimer le jalon',
    'milestoneTitle': 'Titre', 'milestoneDueDate': 'Date d\'échéance',
    'milestoneState': 'État', 'milestoneStateOpen': 'Ouvert',
    'milestoneStateClosed': 'Fermé',
    'createLabel': 'Créer une étiquette',
    'editLabel': 'Modifier l\'étiquette',
    'deleteLabel': 'Supprimer l\'étiquette',
    'labelName': 'Nom', 'labelNameHint': 'ex: bug',
    'labelColor': 'Couleur',
    'createWebhook': 'Créer un webhook',
    'editWebhook': 'Modifier le webhook',
    'deleteWebhook': 'Supprimer le webhook',
    'webhookActive': 'Actif', 'webhookInactive': 'Inactif',
    'webhookType': 'Type',
    'filterByActor': 'Filtrer par acteur',
    'filterByStatus': 'Filtrer par statut',
    'reviews': 'Relectures',
    'allRepos': 'Tous les dépôts',
    'units': 'Unités', 'permission': 'Permission',
    'commit': 'Commit', 'sha': 'SHA',
    'branch': 'Branche', 'author': 'Auteur',
    'jobs': 'Tâches', 'status': 'Statut',
    'https': 'HTTPS', 'ssh': 'SSH', 'id': 'ID', 'api': 'API', 'ui': 'UI',
    'filesChanged': 'Fichiers modifiés',
    'noFilesChanged': 'Aucun fichier modifié',
    'clear': 'Effacer', 'untitled': 'Sans titre',
    'download': 'Télécharger', 'preview': 'Aperçu',
    'ok': 'OK',
  },
}

def translate_file(locale, trans):
    path = os.path.join(D, f'app_{locale}.arb')
    data = json.load(open(path, 'r', encoding='utf-8'))
    count = 0
    for k, v in trans.items():
        if k in data and data[k] == en.get(k, ''):
            data[k] = v
            count += 1
    json.dump(data, open(path, 'w', encoding='utf-8'), indent=2, ensure_ascii=False)
    open(path, 'a').write('\n')
    return count

for locale, trans in translations.items():
    c = translate_file(locale, trans)
    print(f'{locale}: translated {c} keys')
